//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QiraatDivider {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_US_resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US_resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QiraatDivider.en-US.resources", typeof(en_US_resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string ARE_YOU_SURE {
            get {
                return ResourceManager.GetString("ARE_YOU_SURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        internal static string CHOOSE {
            get {
                return ResourceManager.GetString("CHOOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Marks.
        /// </summary>
        internal static string CLEAR_MARKS {
            get {
                return ResourceManager.GetString("CLEAR_MARKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string CONFIRM {
            get {
                return ResourceManager.GetString("CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cue Files|*.cue.
        /// </summary>
        internal static string CUE_FILES {
            get {
                return ResourceManager.GetString("CUE_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected.
        /// </summary>
        internal static string DELETE_SELECTED {
            get {
                return ResourceManager.GetString("DELETE_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Sura no.
        /// </summary>
        internal static string ENTER_SURA_NO {
            get {
                return ResourceManager.GetString("ENTER_SURA_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred..
        /// </summary>
        internal static string ERROR_OCCURRED {
            get {
                return ResourceManager.GetString("ERROR_OCCURRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export completed..
        /// </summary>
        internal static string EXPORT_COMPLETED {
            get {
                return ResourceManager.GetString("EXPORT_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Cue.
        /// </summary>
        internal static string EXPORT_CUE {
            get {
                return ResourceManager.GetString("EXPORT_CUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Marks.
        /// </summary>
        internal static string EXPORT_MARKS {
            get {
                return ResourceManager.GetString("EXPORT_MARKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name:.
        /// </summary>
        internal static string FILE_NAME {
            get {
                return ResourceManager.GetString("FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Marks.
        /// </summary>
        internal static string IMPORT_MARKS {
            get {
                return ResourceManager.GetString("IMPORT_MARKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load completed..
        /// </summary>
        internal static string LOAD_COMPLETED {
            get {
                return ResourceManager.GetString("LOAD_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to Selected Position.
        /// </summary>
        internal static string MOVE_TO_SELECTED_POSITION {
            get {
                return ResourceManager.GetString("MOVE_TO_SELECTED_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mp3 Files|*.mp3.
        /// </summary>
        internal static string MP3_FILES {
            get {
                return ResourceManager.GetString("MP3_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put Mark (F10).
        /// </summary>
        internal static string PUT_MARK {
            get {
                return ResourceManager.GetString("PUT_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save completed..
        /// </summary>
        internal static string SAVE_COMPLETED {
            get {
                return ResourceManager.GetString("SAVE_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed:.
        /// </summary>
        internal static string SPEED {
            get {
                return ResourceManager.GetString("SPEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sura No:.
        /// </summary>
        internal static string SURA_NO {
            get {
                return ResourceManager.GetString("SURA_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qiraat Divider.
        /// </summary>
        internal static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml Files|*.xml.
        /// </summary>
        internal static string XML_FILES {
            get {
                return ResourceManager.GetString("XML_FILES", resourceCulture);
            }
        }
    }
}
