//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QiraatDivider {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class tr_TR_resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal tr_TR_resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QiraatDivider.tr-TR.resources", typeof(tr_TR_resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emin misiniz?.
        /// </summary>
        internal static string ARE_YOU_SURE {
            get {
                return ResourceManager.GetString("ARE_YOU_SURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seç.
        /// </summary>
        internal static string CHOOSE {
            get {
                return ResourceManager.GetString("CHOOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşaretleri Temizle.
        /// </summary>
        internal static string CLEAR_MARKS {
            get {
                return ResourceManager.GetString("CLEAR_MARKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onay.
        /// </summary>
        internal static string CONFIRM {
            get {
                return ResourceManager.GetString("CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cue Dosyaları|*.cue.
        /// </summary>
        internal static string CUE_FILES {
            get {
                return ResourceManager.GetString("CUE_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçiliyi Sil.
        /// </summary>
        internal static string DELETE_SELECTED {
            get {
                return ResourceManager.GetString("DELETE_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure no giriniz..
        /// </summary>
        internal static string ENTER_SURA_NO {
            get {
                return ResourceManager.GetString("ENTER_SURA_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hata oluştu..
        /// </summary>
        internal static string ERROR_OCCURRED {
            get {
                return ResourceManager.GetString("ERROR_OCCURRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dışarı aktarma tamamlandı..
        /// </summary>
        internal static string EXPORT_COMPLETED {
            get {
                return ResourceManager.GetString("EXPORT_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cue&apos;ye Aktar.
        /// </summary>
        internal static string EXPORT_CUE {
            get {
                return ResourceManager.GetString("EXPORT_CUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dışarı Ver.
        /// </summary>
        internal static string EXPORT_MARKS {
            get {
                return ResourceManager.GetString("EXPORT_MARKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Adı:.
        /// </summary>
        internal static string FILE_NAME {
            get {
                return ResourceManager.GetString("FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçeri Al.
        /// </summary>
        internal static string IMPORT_MARKS {
            get {
                return ResourceManager.GetString("IMPORT_MARKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil:.
        /// </summary>
        internal static string LANGUAGE {
            get {
                return ResourceManager.GetString("LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yükleme tamamlandı..
        /// </summary>
        internal static string LOAD_COMPLETED {
            get {
                return ResourceManager.GetString("LOAD_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçili İşarete Git.
        /// </summary>
        internal static string MOVE_TO_SELECTED_POSITION {
            get {
                return ResourceManager.GetString("MOVE_TO_SELECTED_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mp3 Dosyaları|*.mp3.
        /// </summary>
        internal static string MP3_FILES {
            get {
                return ResourceManager.GetString("MP3_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşaret Koy (F10).
        /// </summary>
        internal static string PUT_MARK {
            get {
                return ResourceManager.GetString("PUT_MARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt işlemi tamamlandı..
        /// </summary>
        internal static string SAVE_COMPLETED {
            get {
                return ResourceManager.GetString("SAVE_COMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hız:.
        /// </summary>
        internal static string SPEED {
            get {
                return ResourceManager.GetString("SPEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        internal static string STATUS {
            get {
                return ResourceManager.GetString("STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure No:.
        /// </summary>
        internal static string SURA_NO {
            get {
                return ResourceManager.GetString("SURA_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kıraat Bölücü.
        /// </summary>
        internal static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml Dosyaları|*.xml.
        /// </summary>
        internal static string XML_FILES {
            get {
                return ResourceManager.GetString("XML_FILES", resourceCulture);
            }
        }
    }
}
